# Generated by Django 6.0.5 on 2026-05-29 16:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('idea_input', models.TextField()),
                ('stack_target', models.CharField(default='Django', max_length=100)),
                ('complexity_level', models.CharField(choices=[('mvp', 'MVP'), ('complete', 'Completo'), ('enterprise', 'Enterprise')], default='complete', max_length=20)),
                ('focus_tags', models.JSONField(default=list)),
                ('generated_content', models.TextField(blank=True)),
                ('complexity_score', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('complexity_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('saved', 'Salvo'), ('archived', 'Arquivado'), ('deleted', 'Deletado')], default='draft', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('prompts', models.ManyToManyField(blank=True, to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'Coleção',
            },
        ),
        migrations.CreateModel(
            name='RefinementSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messages', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinement_sessions', to='prompts.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.tag')),
            ],
            options={
                'unique_together': {('prompt', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, through='prompts.PromptTag', to='prompts.tag'),
        ),
        migrations.CreateModel(
            name='PromptSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_number', models.PositiveSmallIntegerField()),
                ('section_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='prompts.prompt')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('prompt', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveSmallIntegerField()),
                ('content_snapshot', models.TextField()),
                ('change_summary', models.TextField(blank=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('prompt', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['user', 'status'], name='prompts_pro_user_id_226c80_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['created_at'], name='prompts_pro_created_969304_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='prompts_pro_search__fabbae_gin'),
        ),
    ]
