# Generated by Django 6.0.5 on 2026-05-29 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('crm', 'CRM'), ('erp', 'ERP'), ('saas', 'SaaS'), ('ecommerce', 'E-commerce'), ('blog', 'Blog'), ('api', 'API-only'), ('marketplace', 'Marketplace'), ('other', 'Outro')], default='other', max_length=20)),
                ('content', models.TextField()),
                ('stack_target', models.CharField(default='Django', max_length=100)),
                ('is_official', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template',
                'ordering': ['-is_official', '-use_count'],
            },
        ),
    ]
